services:
  db:
    image: postgres:13
    container_name: devops_db
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: dindygomez
      POSTGRES_PASSWORD: postgres
      TZ: America/Toronto
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devops-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dindygomez@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123!
      TZ: America/Toronto
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      TZ: America/Toronto
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devops-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: devops_db      
      DB_USER: dindygomez     
      DB_PASSWORD: postgres 
      DB_HOST: db
      DB_PORT: 5432
      TZ: America/Toronto
    depends_on:
      - db
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  db_data:
