version: '3.8' # for Docker Swarm

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      TZ: America/Toronto
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devops-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: gcr.io/micro-docker-test/deploy-backend:latest
    ports:
      - "5000:5000"
    environment:
      DB_NAME: devops_db      
      DB_USER: admin     
      DB_PASSWORD: postgres 
      DB_HOST: db
      DB_PORT: 5432
      TZ: America/Toronto
    depends_on:
      - db
    networks:
      - devops-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: gcr.io/micro-docker-test/deploy-frontend:latest
    environment:
      TZ: America/Toronto
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devops-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  devops-network:
    driver: overlay  #for Docker Swarm

volumes:
  db_data:
