apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-namespace
data:
  DB_HOST: "postgres-service.postgres-namespace.svc.cluster.local"
  DB_NAME: "devops_db" 
  DB_USER: "admin"
  DB_PORT: "5432"
  TZ: "America/Toronto"