apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 34.27.58.52
  selector:
    app: deploy-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000