apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 34.172.138.231
  selector:
    app: deploy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  
