apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  selector:
    app: deploy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
