apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend-deployment
  namespace: frontend-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-frontend
  template:
    metadata:
      labels:
        app: deploy-frontend
    spec:
      containers:
      - name: deploy-frontend-container
        image: gcr.io/micro-docker-test/deploy-frontend:latest
        ports:
        - containerPort: 3000
